### PR TITLE
Add Hypebright blog by Veerle

### PR DESCRIPTION
**Pull request by hypebright**
Adding Hypebright's blog to the list

### CODE REVIEW

**Comment by cosimameyer** [comment]
Thanks so much for contributing, @hypebright! 🥳 I don't have a computer at hand right now and will look into it after the weekend 😊

**Comment by cosimameyer** [comment]
@hypebright Apologies that it took me so long and thanks for your patience! 🤗  

All looks good, just one small follow-up: It looks like your RSS feed is not working correctly (see [here](https://simplepie.org/demo/?feed=https%3A%2F%2Fhypebright.nl%2Findex.php%2Fen%2Fhome-en%2Fblog%2Fcategory%2Fr%2Ffeed%2F)). I checked the source code of your website and it looks like this is your current RSS feed: `https://hypebright.nl/index.php/en/feed/` ([here's the output](https://simplepie.org/demo/?feed=https%3A%2F%2Fhypebright.nl%2Findex.php%2Fen%2Ffeed%2F)). I understand that you intend to sort by R-specific posts - which I appreciate ☺️ I wonder why it's not working the way you intend it to. On which framework is your website built? And do you use categories when writing posts? (I don't see them on the frontend, but they may still be active in the background)

**Comment by hypebright** [comment]
> All looks good, just one small follow-up: It looks like your RSS feed is not working correctly (see [here](https://simplepie.org/demo/?feed=https%3A%2F%2Fhypebright.nl%2Findex.php%2Fen%2Fhome-en%2Fblog%2Fcategory%2Fr%2Ffeed%2F)). I checked the source code of your website and it looks like this is your current RSS feed: `https://hypebright.nl/index.php/en/feed/` ([here's the output](https://simplepie.org/demo/?feed=https%3A%2F%2Fhypebright.nl%2Findex.php%2Fen%2Ffeed%2F)). I understand that you intend to sort by R-specific posts - which I appreciate ☺️ I wonder why it's not working the way you intend it to. On which framework is your website built? And do you use categories when writing posts? (I don't see them on the frontend, but they may still be active in the background)

@cosimameyer hmm I'm using WordPress and do use categories, this is the R category page: https://hypebright.nl/index.php/en/category/r-en/, but as far as I can see it indeed falls back to https://hypebright.nl/index.php/en/feed/, which also contains other types of categories 🤔 

Perhaps I can use this https://hypebright.nl/index.php/en/category/r-en/feed, that seems to work alright (see output [here](https://simplepie.org/demo/?feed=https%3A%2F%2Fhypebright.nl%2Findex.php%2Fen%2Fcategory%2Fr-en%2Ffeed)). Let me know and I can change it!

**Comment by cosimameyer** [comment]
@hypebright Perfect, thanks for looking the categories up! It should be `https://hypebright.nl/index.php/en/category/r-en/feed/` ☺️ Please, feel free and make the change - I'll then run the tests and merge your PR ☺️

**Comment by hypebright** [comment]
@cosimameyer done ✅

**Review by cosimameyer — APPROVED** [review]

**Pull request merged**
