### PR TITLE
Fix Mastodon link

### PR DESCRIPTION
**Pull request by EllaKaye**

### CODE REVIEW

**Comment by drmowinckels** [comment]
Hey! I think the original is what we want, really. It will create a direct link to your fosstodon account on our webpages etc.

**Comment by EllaKaye** [comment]
Oh, OK! I noticed others had done it differently and thought mine was wrong, but happy to know that it's not!

**Comment by cosimameyer** [comment]
Sorry for “opening” it again ☺️ 
The bot needs the “new” format that Ella added (I've been manually editing the format for Ella’s post in the past few days to tag Ella properly). I think we need both formats. I see two options: We could either 1) add a function that creates the Mastodon URL (= “old” format that I believe is needed for the website) or 2) a function that creates the handle (= “new” format for the bot on Mastodon; it would also mean updating all “newly” changed entries because they all follow the “new” format). 

I have a slight preference for option 1 because I see the dependencies with the bot.  So I think it would be easier to write a function that creates the Mastodon URL and leave the “handle” (new format) as it is. But I don’t have the full understanding of how often the function would need to run for the website and how many dependencies are involved, etc. so if it’s easier, I can also add the function to the bot.

**Comment by EllaKaye** [comment]
Thanks @cosimameyer. That is why I opened the pull request, because I saw that the bot had tooted about one of my old blog posts but I hadn't been tagged. When I checked the other blogs in this repo, I saw they were done the 'new' way, hence the pull request for the change. But then I saw that I was being tagged and assumed it was fixed, but now I know that Cosima is manually editing the bot's posts, I can see the dilemma.

So, I'm reopening the pull request for now and will leave it to you both to decide on which of options 1 or 2 is better. Then you can either merge the pull request or close it without merging it depending on which you go for.

Thanks for all your work on this 😄

**Comment by cosimameyer** [comment]
Thanks! ☺️ @drmowinckel, let me know what works best and what your preferences are ☺️

**Comment by DrMowinckel** [comment]
> Thanks! ☺️ @drmowinckel, let me know what works best and what your preferences are ☺️

Hey, you tagged the wrong person, I believe.

**Comment by cosimameyer** [comment]
> > Thanks! ☺️ @DrMowinckel, let me know what works best and what your preferences are ☺️
> 
> Hey, you tagged the wrong person, I believe.

You're right - thank you! ☺️

**Comment by drmowinckels** [comment]
right @cosimameyer . I see! Then we need it like that....  I'll have a think about how else I can solve it for the website, though it will require a lot of annoying string work, I'll see what I can do :)

**Pull request merged**
