### PR TITLE
Test adding new file

### PR DESCRIPTION
**Pull request by maelle**
I wanted to test the instructions but my blog is already in there. 

@Shelmith-Kariuki would you be ok with adding your blog to this list?

@Athanasiamo does the JSON look good?

### CODE REVIEW

**Comment by Athanasiamo** [comment]
json format verification action is passed, so the json looks good. :) Will merge when blog author confirms they'd like to be added to the list :)

**Comment by Shelmith-Kariuki** [comment]
Thank you @maelle . I have included this as part of my afternoon task

**Comment by Shelmith-Kariuki** [comment]
@maelle based on our conversation on Twitter DM, I am okay with the addition

**Comment by Athanasiamo** [comment]
Thank you so much, both of you, for contributing to our list!

**Pull request merged**
