### PR TITLE
Fixing jsonlite lazy load failing

### PR DESCRIPTION
**Pull request by cosimameyer**

### CODE REVIEW

**Comment by cosimameyer** [comment]
@drmowinckels we have an issue with `renv` and our R version. Although our lock defines an older R version, it sources >4.4.0 which is (apparently) known for causing issues in combination with an older renv version. It looks like [this issue](https://github.com/rstudio/renv/issues/1886) is pretty much what we're having as well (screenshot is from [our log](https://github.com/rladies/awesome-rladies-blogs/actions/runs/11651533608/job/32441610304#step:4:32))

image

I changed a few things (also what was suggested in the issue) and added this to our yaml (see commits in this PR):

```
- uses: r-lib/actions/setup-r@v2
    with:
      r-version: renv
```

But I wasn't able to fully solve it. I didn't want to interfere too much with what we have and GitHub told me that you made some changes to our renv - so I wondered if you have a quick idea? If not, happy to look deeper into it :)

**Comment by cosimameyer** [comment]
It looks like it's working now 🎉 I don't want to make any merges that could throw things up (and it's been a while since I worked with `renv`). Can I ask any of you to review the PR if you have the capacity (and energy 🤗) - maybe @drmowinckels or @maelle? ☺️

**Comment by cosimameyer** [comment]
I added all three of you as reviewers (feel free to remove yourself if it doesn't fit into your schedule 🤗) - I just wanted to have a second pair of eyes on this one here so that we can merge it once the build works 😊

**Comment by drmowinckels** [comment]
Hi!

I have an alternate suggestion in #114 that still uses the normal renv setup, which should be more stable over time. I also reordered some operations so that the process is smoother to debug.

**Comment by cosimameyer** [comment]
Obsolete because of #114

**Pull request closed without merging**
