### PR TITLE
remove twitter from drmowinckels

### PR DESCRIPTION
**Pull request by drmowinckels**

### CODE REVIEW

**Review by cosimameyer — APPROVED** [review]

**Comment by cosimameyer** [comment]
It worked 🥳

**Comment by drmowinckels** [comment]
@cosimameyer the auto-review tagger wont choose you right now because you are set to busy :) Just fyi. But I think I have made the settings now that it will choose from the website team and assign tasks equally across the team

**Comment by cosimameyer** [comment]
Thanks for the reminder, I removed it :) The holidays are over :D

**Comment by drmowinckels** [comment]
just to be clear, this is a true PR. I do want to remove my twitter :)

**Comment by cosimameyer** [comment]
Sounds good :) Here's the next question (I know that it's handled differently in teams): Should the persons who opened the PR close it themselves (if they have permission) or should the person who did the review close the PR? Most teams used the first approach because the person who opened the PR is usually also responsible for merge conflicts and a very last check - but I'm happy to go with option 2 as well :)

**Comment by drmowinckels** [comment]
I've operated with me closing everything, as the person merging. The PR is still there in case it needs reopening for some reason.

**Comment by cosimameyer** [comment]
Excellent, that sounds great! So that means: the person who reviews the PR will also close it?

**Comment by drmowinckels** [comment]
yes, I'd say so. At least, the person merging, which in most cases will also be the one reviewing, I think?

**Comment by cosimameyer** [comment]
Sorry, yes - I was unspecific :D close = merge for me here :) But then I'll go ahead and squash & merge this one to get the routine started.

**Pull request merged**
