### PR TITLE
Add Bluesky for Cara

### PR DESCRIPTION
**Pull request by cosimameyer**
Hi @cararthompson,  

I'm working on adding a Bluesky integration for the R-Ladies bot and saw that you're also on Bluesky. Please let me know 

- if you agree to add your handle here as well so that the bot can use it to tag you when posting about your posts
- if you're also OK to be featured in an R-Ladies starter pack

Thank you ☺️

### CODE REVIEW

**Comment by cararthompson** [comment]
Thanks for thinking of me. Yes please, I'd love to be included. There seems to be an error in the checks above. Let me know if you need me to do anything. Thanks again!

**Comment by cosimameyer** [comment]
Thanks so much 💜 the tests should be good in a bit :)

**Comment by cosimameyer** [comment]
---- 

Ref #97  - Should be added to starter pack

**Comment by cararthompson** [comment]
Thank you!

**Pull request merged**
