### PR TITLE
Adding cararthompson.com to the list

### PR DESCRIPTION
**Pull request by cararthompson**
Hi @Athanasiamo ! Thanks for creating this resource. Let me know if there's more you need me to do to be added.

### CODE REVIEW

**Comment by Athanasiamo** [comment]
Thank you @cararthompson for submitting!

Could you please remove all the `//required` strings from the file. These were not intended to stay, but just highlight fields that needed to be completed.

**Comment by cararthompson** [comment]
Thanks for keeping me right @Athanasiamo ! I made the requested changes and added a subtitle. Let me know if you need me to do anything more.

**Comment by Athanasiamo** [comment]
Thank you for adding your blog to the list and for making free and open R content 😊 🥳 🎉

**Comment by cararthompson** [comment]
Thanks! 🥳

**Pull request merged**
