### PR TITLE
Create lgibson7.quarto.pub.json

### PR DESCRIPTION
**Pull request by cosimameyer**
Refers to this issue #65

### CODE REVIEW

**Comment by drmowinckels** [comment]
@cosimameyer I'm happy to let you start merging and approving these changes too from now on :)

**Comment by cosimameyer** [comment]
Thanks for your trust! What would be our policy for this repository? Do we go by always having one reviewer per PR? Or do we merge small(er) PRs also without a review?

**Comment by drmowinckels** [comment]
those are all great questions I have no answers to :P Its mainly been me dealing with it, so I have not really made a procedure :P I guess this is a great time to start making that!

**Comment by cosimameyer** [comment]
That sounds great! My feeling is that it might be good to have one reviewer per PR (it can slow down development processes but my experience is that it gives more stability and security (four eyes are just more likely to catch typos and errors :D)) - but I'm also open for other procedures :)

**Pull request merged**
