### PR TITLE
Add cghlewis.com

### PR DESCRIPTION
**Pull request by Cghlewis**
I added my website, cghlewis.com to the blog folder.

### CODE REVIEW

**Comment by cosimameyer** [comment]
Thank you, I'll look it! :) If you're not already part of it, would you be OK with being added to a Bluesky starter pack for R-Ladies? :)

**Comment by Cghlewis** [comment]
> @Cghlewis Thank you, I'll look it! :) If you're not already part of it, would you be OK with being added to a Bluesky starter pack for R-Ladies? :)

Thank you! I believe I'm already in the R-Ladies starter pack!

**Comment by cosimameyer** [comment]
--- 

Ref: #97 If not already in the starter pack, please also add Crystal :)

**Comment by cosimameyer** [comment]
Awesome, thanks! I tagged you (just in case) to double check and add you if you're not already in it :)

**Pull request merged**
