### PR TITLE
Add Julia's Bluesky handle

### PR DESCRIPTION
**Pull request by cosimameyer**
Hi @juliasilge,  

I'm working on adding a Bluesky integration for the R-Ladies bot and saw that you're also on Bluesky. Please let me know 

- if you agree to add your handle here as well so that the bot can use it to tag you when posting about your posts
- if you're also OK to be featured in an R-Ladies starter pack

Thank you ☺️

### CODE REVIEW

**Review by juliasilge — APPROVED** [review]
Looks great! Thank you so much 💟

**Comment by cosimameyer** [comment]
@juliasilge  Thank you 💜 I assume you’re already on the R-Ladies starter pack at bluesky but just to double check - is it ok for you to be there? ☺️

**Comment by juliasilge** [comment]
@cosimameyer Yes, that is fine with me!

**Comment by cosimameyer** [comment]
—-

for reference: #97

**Pull request merged**
