### PR TITLE
Create soyandrea.netlify.app.json

### PR DESCRIPTION
**Pull request by SoyAndrea**
Hi, tell me if you need something else.  Thank you

### CODE REVIEW

**Comment by Athanasiamo** [comment]
This is great. Thank you @SoyAndrea for adding your blog to our list.
Before I can merge it, could you please rename the file to not include the default string `your-blog-url.com.json` at the end? 

You can do this on GitHub following this description:
https://docs.github.com/en/repositories/working-with-files/managing-files/renaming-a-file

**Comment by SoyAndrea** [comment]
Hi Athanasia!  Thanks for your recommendation, I had not seen it. I renamed the file, can you tell me if it is ok?  :)

**Comment by SoyAndrea** [comment]
Hi @Athanasiamo , I don't know if I made the changes correctly, can you let me know?

**Comment by Athanasiamo** [comment]
Hi @SoyAndrea , sorry for being late. I cannot see that the file has changed name.  To change the name, you need to alter it at this link: https://github.com/SoyAndrea/awesome-rladies-blogs/blob/patch-1/blogs/soyandrea.netlify.app.jsonyour-blog-url.com.json

Let me know what other aid you might need :)

**Comment by SoyAndrea** [comment]
Hi @Athanasiamo, no problem.  I made the rename change now but I don't know if it is ok, can you confirm when you can? :)

**Review by Athanasiamo — APPROVED** [review]

**Comment by Athanasiamo** [comment]
Great! That's all that was left!

Thank you for adding your blog to the list and for making free and open R content 😊 🥳 🎉

**Pull request merged**
