### PR TITLE
Update and rename silvia.rbind.io.json to silviacanelon.json

### PR DESCRIPTION
**Pull request by spcanelon**

### CODE REVIEW

**Comment by cosimameyer** [comment]
@maelle if you want, I’m happy to take over this PR and review it 🙌

**Review by cosimameyer — CHANGES_REQUESTED** [review]
Thanks for updating your entry 🥳  

Looks good so far - just one very small request: can you rename the JSON to `silviacanelon.com.json`?

**Comment by spcanelon** [comment]
> Thanks for updating your entry 🥳
> 
> Looks good so far - just one very small request: can you rename the JSON to `silviacanelon.com.json`?

Done! Thanks Cosima 🥳

**Review by cosimameyer — APPROVED** [review]

**Comment by cosimameyer** [comment]
Amazing, thanks so much 🥳

**Pull request merged**
